name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  push_image:
    name: Push image
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Configure ACR creds
        uses: Azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
     
      - name: Get version number with hash
        run: echo "VERSION=$(cat ./.VERSION)-RC-$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

      - name: Get version number
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: echo "VERSION=$(cat ./.VERSION)" >> $GITHUB_ENV
    
      - name: Print $GITHUB_ENV
        run: echo "$GITHUB_ENV"